# Konfigurace Mosquitto
listener 1883
allow_anonymous true

# WebSockets listener na portu 9001
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true

# --- BRIDGE NA ŠKOLNÍ BROKER ---
connection school-bridge
address 158.196.109.41:1883
remote_username YOUR_USERNAME
remote_password YOUR_PASSWORD

# Přenášet vše z esp-now/#
topic esp-now/# in 0
