[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ 6.11.0
board = esp32dev
framework = espidf
monitor_speed = 115200
lib_extra_dirs = ../Shared
build_flags = 
    -I ../Shared/Common/include
