[agent]
  debug = true
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "YOUR_INFLUX_TOKEN"
  organization = "my-org"
  bucket = "my-bucket"

[[inputs.mqtt_consumer]]
  servers = ["tcp://YOUR_MQTT_BROKER_IP:1883"]
  username = "YOUR_USERNAME"
  password = "YOUR_PASSWORD"
  topics = [
    "esp-now/infra/sensors/+",
    "esp-now/infra/routers/+",
    "esp-now/infra/gateway_info",
  ]
  qos = 0
  connection_timeout = "30s"
  data_format = "json"
  json_string_fields = ["data", "id", "relay", "link", "type"]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "esp-now/infra/sensors/+"
    measurement = "_/_/measurement/_"
    tags = "_/_/_/id"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "esp-now/infra/routers/+"
    measurement = "_/_/measurement/_"
    tags = "_/_/_/id"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "esp-now/infra/gateway_info"
    measurement = "_/_/measurement"

# Dekódování BME688 HEX dat
[[processors.starlark]]
  script = "/etc/telegraf/decode_bme688.star"
