[platformio]
default_envs = T-SIM7000G

[env:T-SIM7000G]
platform = espressif32 @ 6.11.0
board = esp32dev
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_upload.flash_size = 2MB
framework = espidf
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -I ../Shared/Common/include
    -D TINY_GSM_MODEM_SIM7000

board_build.partitions = partitions_singleapp_large.csv
