idf_component_register(SRCS "main.cpp"
                             "DataManager.cpp"
                             "MqttManager.cpp"
                             "SerialBridge.cpp"
                             "WifiManager.cpp"
                             "WebServer.cpp"
                             "LedManager.cpp"
                       INCLUDE_DIRS ".")